apiVersion: v1
kind: Service
metadata:
  labels:
    service: ocr-backend
  name: ocr-backend
  namespace: backend
spec:
  ports:
  - name: "8000"
    port: 8000
    targetPort: 8000
  selector:
    service: ocr-backend